version: 0.2

phases:
  pre_build:
    commands:
      - echo pre Build on `date`
      - . "$(pwd)/.env"
      - git submodule init
      - git config -f .gitmodules submodule.submodule/aws_cli_container.url ${AWS_CLI_CONTAINER_URL}
      - git config -f .gitmodules submodule.submodule/pike_container.url ${PIKE_CONTAINER_URL}
      - git config -f .gitmodules submodule.submodule/terraform_container.url ${TERRAFORM_CONTAINER_URL}
      - cat .gitmodules
      - git submodule update
      - ls -la
      - ls -la "$(pwd)/submodule"

  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo post Build on `date`

