version: 0.2

phases:
  pre_build:
    commands:
      - echo pre Build on `date`
      - whoami && pwd && ls -la
      - . "$(pwd)/.env"
      - env
      - git config -f .gitmodules submodule.submodule/pike_container.url https://git-codecommit.us-east-1.amazonaws.com/v1/repos/pike_container

  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo post Build on `date`

